defmodule NixSwarm.Autoscaler do
  @moduledoc """
  Leaderless, CPU-only autoscaling for Nix-declared stateless services.

  Each service has a temporary deterministic owner selected from the same
  stabilized membership used for placement. Decisions are observations, not
  desired state: they expire on configuration or membership changes and always
  remain inside the limits generated by Nix.
  """

  use GenServer

  alias NixSwarm.Executor
  alias NixSwarm.Placement

  @decision_ttl_multiplier 4
  @scale_down_hysteresis 0.70

  def start_link(opts), do: GenServer.start_link(__MODULE__, opts, name: __MODULE__)

  def targets do
    if Process.whereis(__MODULE__), do: GenServer.call(__MODULE__, :targets), else: %{}
  end

  def snapshot do
    if Process.whereis(__MODULE__),
      do: GenServer.call(__MODULE__, :snapshot),
      else: empty_snapshot()
  end

  def accept_decision(decision) when is_map(decision) do
    if Process.whereis(__MODULE__), do: GenServer.cast(__MODULE__, {:decision, decision})
    :ok
  end

  @doc false
  def recommend_target(current, utilization, policy) do
    raw = ceil(current * utilization / policy.cpu_target_percent)

    cond do
      utilization > policy.cpu_target_percent and current < policy.max_replicas ->
        current
        |> Kernel.+(policy.max_step)
        |> min(max(raw, current + 1))
        |> min(policy.max_replicas)

      utilization < policy.cpu_target_percent * @scale_down_hysteresis and
          current > policy.min_replicas ->
        current
        |> Kernel.-(policy.max_step)
        |> max(raw)
        |> max(policy.min_replicas)

      true ->
        current
    end
  end

  @impl true
  def init(_opts) do
    config = NixSwarm.Config.current()
    digest = NixSwarm.Config.digest_for(config)

    state = %{
      config_digest: digest,
      targets: restored_targets(config, digest),
      membership_fingerprint: membership_fingerprint(NixSwarm.Cluster.placement_nodes()),
      previous_counters: %{},
      local_samples: %{},
      trends: %{},
      last_changed_ms: %{},
      decisions: %{}
    }

    schedule_tick()
    {:ok, state}
  end

  @impl true
  def handle_call(:targets, _from, state), do: {:reply, state.targets, state}

  def handle_call(:snapshot, _from, state) do
    {:reply,
     %{
       node: Node.self(),
       config_digest: state.config_digest,
       samples: state.local_samples,
       targets: state.targets
     }, state}
  end

  @impl true
  def handle_cast({:decision, decision}, state) do
    {:noreply, maybe_accept_decision(state, decision)}
  end

  @impl true
  def handle_info(:tick, state) do
    state =
      state
      |> refresh_config()
      |> refresh_membership()
      |> expire_invalid_decisions()
      |> sample_owned_units()
      |> evaluate_owned_services()

    schedule_tick()
    {:noreply, state}
  end

  defp refresh_config(state) do
    config = NixSwarm.Config.current()
    digest = NixSwarm.Config.digest_for(config)

    if digest == state.config_digest do
      state
    else
      %{
        state
        | config_digest: digest,
          targets: initial_targets(config),
          membership_fingerprint: membership_fingerprint(NixSwarm.Cluster.placement_nodes()),
          previous_counters: %{},
          local_samples: %{},
          trends: %{},
          last_changed_ms: %{},
          decisions: %{}
      }
    end
  end

  defp refresh_membership(state) do
    fingerprint = membership_fingerprint(NixSwarm.Cluster.placement_nodes())

    if fingerprint == state.membership_fingerprint do
      state
    else
      %{
        state
        | membership_fingerprint: fingerprint,
          previous_counters: %{},
          local_samples: %{},
          trends: %{},
          last_changed_ms: %{},
          decisions: %{}
      }
    end
  end

  defp sample_owned_units(state) do
    config = NixSwarm.Config.current()
    placement_nodes = NixSwarm.Cluster.placement_nodes()
    now_ns = System.monotonic_time(:nanosecond)

    owned = Placement.local_units(Node.self(), config, placement_nodes, state.targets)

    counters =
      owned
      |> Enum.group_by(& &1.service)
      |> Map.new(fn {service, slots} ->
        total =
          Enum.reduce(slots, 0, fn slot, sum -> sum + Executor.unit_cpu_usage(slot.unit) end)

        {service, %{usage_ns: total, unit_count: length(slots), sampled_at_ns: now_ns}}
      end)

    samples =
      Map.new(counters, fn {service, current} ->
        utilization =
          case Map.get(state.previous_counters, service) do
            %{usage_ns: previous_usage, sampled_at_ns: previous_at}
            when current.usage_ns >= previous_usage and now_ns > previous_at and
                   current.unit_count > 0 ->
              (current.usage_ns - previous_usage) * 100.0 /
                ((now_ns - previous_at) * current.unit_count)

            _previous ->
              nil
          end

        {service,
         %{
           cpu_percent: utilization,
           unit_count: current.unit_count,
           sampled_at_ms: System.system_time(:millisecond)
         }}
      end)

    %{state | previous_counters: counters, local_samples: samples}
  end

  defp evaluate_owned_services(state) do
    config = NixSwarm.Config.current()
    placement_nodes = NixSwarm.Cluster.placement_nodes()

    Enum.reduce(config.services, state, fn service, acc ->
      if service.autoscaling.enabled and
           Placement.scaler_owner(service, placement_nodes, config.nodes) == Node.self() do
        evaluate_service(acc, service, placement_nodes)
      else
        acc
      end
    end)
  end

  defp evaluate_service(state, service, placement_nodes) do
    live_nodes = NixSwarm.Cluster.live_nodes()

    snapshots =
      NixSwarm.RPC.multicall(live_nodes, __MODULE__, :snapshot, [])
      |> Enum.flat_map(fn
        {_node, {:ok, %{config_digest: digest} = snapshot}} when digest == state.config_digest ->
          [snapshot]

        _failure ->
          []
      end)

    case aggregate_sample(snapshots, service.name) do
      nil ->
        state

      utilization ->
        now_ms = System.monotonic_time(:millisecond)
        state = ensure_current_decision(state, service, placement_nodes, now_ms)
        {direction, state} = track_direction(state, service, utilization, now_ms)

        if decision_due?(state, service, direction, now_ms) do
          current = Map.get(state.targets, service.name, service.replicas)
          next = recommend_target(current, utilization, service.autoscaling)

          cond do
            next == current ->
              refresh_current_decision(state, service, placement_nodes, now_ms)

            next < current and not safe_to_scale_down?(live_nodes, state.config_digest) ->
              refresh_current_decision(state, service, placement_nodes, now_ms)

            true ->
              publish_decision(state, service, next, placement_nodes, now_ms)
          end
        else
          refresh_current_decision(state, service, placement_nodes, now_ms)
        end
    end
  end

  @doc false
  def aggregate_sample(snapshots, service_name) do
    samples =
      snapshots
      |> Enum.flat_map(fn snapshot ->
        case get_in(snapshot, [:samples, service_name]) do
          %{cpu_percent: value, unit_count: count} when is_number(value) and count > 0 ->
            [{value, count}]

          _missing ->
            []
        end
      end)

    case samples do
      [] ->
        nil

      values ->
        total_units = Enum.sum(Enum.map(values, &elem(&1, 1)))
        Enum.sum(Enum.map(values, fn {value, count} -> value * count end)) / total_units
    end
  end

  @doc false
  def valid_decision?(
        decision,
        service,
        config_digest,
        placement_nodes,
        config,
        now_ms \\ System.system_time(:millisecond)
      ) do
    service != nil and service.autoscaling.enabled and
      decision.config_digest == config_digest and
      decision.owner == Placement.scaler_owner(service, placement_nodes, config.nodes) and
      decision.membership_fingerprint == membership_fingerprint(placement_nodes) and
      decision.expires_at_ms >= now_ms and
      decision.target in service.autoscaling.min_replicas..service.autoscaling.max_replicas
  end

  defp track_direction(state, service, utilization, now_ms) do
    policy = service.autoscaling

    direction =
      cond do
        utilization > policy.cpu_target_percent -> :up
        utilization < policy.cpu_target_percent * @scale_down_hysteresis -> :down
        true -> :stable
      end

    trend = Map.get(state.trends, service.name)

    trends =
      if trend && trend.direction == direction do
        state.trends
      else
        Map.put(state.trends, service.name, %{direction: direction, since_ms: now_ms})
      end

    {direction, %{state | trends: trends}}
  end

  defp decision_due?(_state, _service, :stable, _now_ms), do: false

  defp decision_due?(state, service, direction, now_ms) do
    trend = Map.fetch!(state.trends, service.name)
    policy = service.autoscaling
    window_ms = policy.sample_window_sec * 1_000

    cooldown_ms =
      case direction do
        :up -> policy.scale_up_cooldown_sec * 1_000
        :down -> policy.scale_down_cooldown_sec * 1_000
      end

    last_changed = Map.get(state.last_changed_ms, service.name, now_ms - cooldown_ms)
    now_ms - trend.since_ms >= window_ms and now_ms - last_changed >= cooldown_ms
  end

  defp safe_to_scale_down?(live_nodes, config_digest) do
    expected = MapSet.new(NixSwarm.Cluster.required_nodes())
    live = MapSet.new(live_nodes)

    digest_results = NixSwarm.RPC.multicall(live_nodes, NixSwarm.API, :config_digest, [])

    expected == live and
      Enum.all?(digest_results, fn
        {_node, {:ok, ^config_digest}} -> true
        _failure -> false
      end)
  end

  defp publish_decision(state, service, target, placement_nodes, now_ms) do
    decision = %{
      service: service.name,
      target: target,
      owner: Node.self(),
      config_digest: state.config_digest,
      membership_fingerprint: membership_fingerprint(placement_nodes),
      issued_at_ms: System.system_time(:millisecond),
      expires_at_ms:
        System.system_time(:millisecond) +
          NixSwarm.Config.runtime().autoscale_interval_ms * @decision_ttl_multiplier
    }

    state = apply_decision(state, decision, now_ms)

    NixSwarm.Cluster.live_nodes()
    |> Enum.reject(&(&1 == Node.self()))
    |> Enum.each(&NixSwarm.RPC.cast(&1, __MODULE__, :accept_decision, [decision]))

    state
  end

  defp refresh_current_decision(state, service, placement_nodes, now_ms) do
    case Map.get(state.decisions, service.name) do
      nil ->
        state

      decision ->
        publish_decision(state, service, decision.target, placement_nodes, now_ms)
    end
  end

  defp ensure_current_decision(state, service, placement_nodes, now_ms) do
    case Map.get(state.decisions, service.name) do
      nil ->
        target = Map.get(state.targets, service.name, service.replicas)
        publish_decision(state, service, target, placement_nodes, now_ms)

      _decision ->
        state
    end
  end

  defp maybe_accept_decision(state, decision) do
    config = NixSwarm.Config.current()
    service = Enum.find(config.services, &(&1.name == Map.get(decision, :service)))
    placement_nodes = NixSwarm.Cluster.placement_nodes()

    valid? =
      valid_decision?(
        decision,
        service,
        state.config_digest,
        placement_nodes,
        config
      )

    if valid?,
      do: apply_decision(state, decision, System.monotonic_time(:millisecond)),
      else: state
  end

  defp apply_decision(state, decision, now_ms) do
    previous = Map.get(state.decisions, decision.service)

    if previous == nil or decision.issued_at_ms >= previous.issued_at_ms do
      target_changed? =
        Map.get(state.targets, decision.service) != decision.target

      if target_changed? and Process.whereis(NixSwarm.Reconciler),
        do: send(NixSwarm.Reconciler, :autoscaling_changed)

      %{
        state
        | targets: Map.put(state.targets, decision.service, decision.target),
          decisions: Map.put(state.decisions, decision.service, decision),
          last_changed_ms:
            if(target_changed?,
              do: Map.put(state.last_changed_ms, decision.service, now_ms),
              else: state.last_changed_ms
            ),
          trends:
            if(target_changed?,
              do: Map.delete(state.trends, decision.service),
              else: state.trends
            )
      }
    else
      state
    end
  end

  defp expire_invalid_decisions(state) do
    config = NixSwarm.Config.current()
    placement_nodes = NixSwarm.Cluster.placement_nodes()
    fingerprint = membership_fingerprint(placement_nodes)
    now_ms = System.system_time(:millisecond)

    valid =
      Map.filter(state.decisions, fn {service_name, decision} ->
        service = Enum.find(config.services, &(&1.name == service_name))

        service != nil and service.autoscaling.enabled and
          decision.config_digest == state.config_digest and
          decision.membership_fingerprint == fingerprint and
          decision.expires_at_ms >= now_ms and
          decision.owner == Placement.scaler_owner(service, placement_nodes, config.nodes)
      end)

    targets =
      valid
      |> Map.new(fn {service, decision} -> {service, decision.target} end)
      |> then(&Map.merge(normalize_targets(config, state.targets), &1))

    %{state | decisions: valid, targets: targets}
  end

  defp restored_targets(config, digest) do
    snapshot = NixSwarm.OperationalState.snapshot()

    if Map.get(snapshot, :config_digest) == digest do
      normalize_targets(config, Map.get(snapshot, :autoscaling_targets, %{}))
    else
      initial_targets(config)
    end
  end

  defp initial_targets(config), do: normalize_targets(config, %{})

  @doc false
  def normalize_targets(config, targets) do
    config.services
    |> Enum.filter(& &1.autoscaling.enabled)
    |> Map.new(fn service ->
      target =
        targets
        |> Map.get(service.name, service.replicas)
        |> max(service.autoscaling.min_replicas)
        |> min(service.autoscaling.max_replicas)

      {service.name, target}
    end)
  end

  @doc false
  def membership_fingerprint(nodes) do
    nodes
    |> Enum.sort()
    |> :erlang.term_to_binary([:deterministic])
    |> then(&:crypto.hash(:sha256, &1))
  end

  defp schedule_tick do
    Process.send_after(self(), :tick, NixSwarm.Config.runtime().autoscale_interval_ms)
  end

  defp empty_snapshot do
    %{node: Node.self(), config_digest: NixSwarm.Config.digest(), samples: %{}, targets: %{}}
  end
end
